# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5UnbYGrRXIuaWqDtEohOFRWXw9dt-c4
"""

import random
import string

def generate_password(length):
    if length < 8 or length > 32:
        raise ValueError("Password length must be between 8 and 32 characters.")

    # Создаем наборы символов
    lowercase_letters = string.ascii_lowercase
    uppercase_letters = string.ascii_uppercase
    digits = string.digits
    special_characters = string.punctuation

    # Гарантируем, что пароль будет содержать хотя бы один символ каждого типа
    password = [
        random.choice(lowercase_letters),
        random.choice(uppercase_letters),
        random.choice(digits),
        random.choice(special_characters)
    ]

    # Добавляем случайные символы до достижения необходимой длины
    all_characters = lowercase_letters + uppercase_letters + digits + special_characters
    password += random.choices(all_characters, k=length-4)

    # Перемешиваем символы пароля
    random.shuffle(password)

    return ''.join(password)

# Пример использования
password_length = 16
password = generate_password(password_length)
print(f"Generated password: {password}")